/* Populated by react-webpack-redux:action */
export const SEARCH = 'SEARCH';
export const EMOTION = 'EMOTION';
export const TYPEAHEAD = 'TYPEAHEAD';
export const FEED = 'FEED';
export const CLEAR = 'CLEAR';
export const CLEANUP = 'CLEANUP';
export const FETCH_SMILEY = 'FETCH_SMILEY';
export const CHART = 'CHART';
export const TIMELINE = 'TIMELINE';
